---
model: "tabs"
task: "rel"
# data related 
known_types: 31
unknown_types: 10
dataset_name: "tacred"
dataset_dir: "data/tacred"
test_ratio: 0.15
# model related 
model_type: "bert"
model_name_or_path: "bert-base-uncased"
cache_dir: "./cache"
supervised_pretrain: true
label_smoothing_alpha: 0.1
token_pooling: "first"
hidden_dim: 256
classifier_layers: 2
# runtime 
num_train_epochs: 3
train_batch_size: 16
accumulate_grad_batches: 2
num_workers: 2
eval_batch_size: 16

