---
model: "etypeclus"
task: "event"
# data
dataset_name: "ace"
dataset_dir: "data/ace"
test_ratio: 0.3 
known_types: 10
unknown_types: 23 
# model 
model_type: "bert"
model_name_or_path: "bert-base-uncased"
cache_dir: "./cache"
temperature: 0.1
distribution: "softmax"
gamma: 5 
# runtime 
num_train_epochs: 50
num_pretrain_epochs: 10
train_batch_size: 64
accumulate_grad_batches: 1
num_workers: 2 
eval_batch_size: 64
learning_rate: 1e-4 

