---
model: "tabs"
task: "event"
# data related 
known_types: 10
unknown_types: 23
dataset_name: "ace"
dataset_dir: "data/ace"
test_ratio: 0.3
# model related 
model_type: "bert"
model_name_or_path: "bert-base-uncased"
cache_dir: "./cache"
label_smoothing_alpha: 0.1
label_smoothing_ramp: 3 
token_pooling: "first"
hidden_dim: 256
kmeans_dim: 256
classifier_layers: 2
pairwise_loss: true
clustering: "kmeans"
kmeans_outlier_alpha: 0.0
consistency_loss: 0.2 
contrastive_loss: 0.0
recon_loss: 0.0
# runtime 
num_train_epochs: 30
num_pretrain_epochs: 0
train_batch_size: 16
accumulate_grad_batches: 2
num_workers: 2
eval_batch_size: 32
check_pl: true

